add bmg distributed test in ci and nightly wheel weekly

diff --git a/.github/actions/linux-uttest/action.yml b/.github/actions/linux-uttest/action.yml
--- a/.github/actions/linux-uttest/action.yml
+++ b/.github/actions/linux-uttest/action.yml
@@ -156,6 +156,36 @@ runs:
           tee ${{ github.workspace }}/ut_log/xpu_distributed/xpu_distributed_test.log
         find ../ -type f -name "*.xml" -exec cp {} ${{ github.workspace }}/ut_log/ \;
 
+    - name: xpu_distributed_bmg
+      shell: timeout 36000 bash -xeu -o pipefail {0}
+      if: ${{ inputs.ut_name == 'xpu_distributed_bmg' }}
+      run: |
+        xpu-smi topology -m
+        mkdir -p ut_log/xpu_distributed_bmg
+
+        rm -rf pytorch/third_party/torch-xpu-ops
+        git clone --depth 1 --branch daisyden/distributed_2.13 \
+          https://github.com/intel/torch-xpu-ops.git \
+          pytorch/third_party/torch-xpu-ops
+
+        XCCL_ENABLE=$(python -c "import torch; print(torch.distributed.is_xccl_available())")
+        if [[ "${XCCL_ENABLE,,}" == 'false' ]] || [[ "${XCCL_ENABLE}" == '0' ]]; then
+          echo -e "[ERROR] XCCL is not enabled"
+          exit 1
+        fi
+        cd pytorch/third_party/torch-xpu-ops/test/xpu
+        export TEMP_DIR=/tmp
+        export BACKEND=xccl
+        export WORLD_SIZE=4
+        export USE_CCL_V2=1
+        uv pip install transformers pulp
+        sudo rm -rf /tmp/torchinductor_jenkins/
+        python -c "import inspect, shutil, torch.testing._internal.distributed.distributed_test as m; shutil.copyfile('distributed/distributed_test.py', inspect.getsourcefile(m) or m.__file__)"
+        python run_distributed_local.py \
+          2> ${{ github.workspace }}/ut_log/xpu_distributed_bmg/xpu_distributed_bmg_test_error.log | \
+          tee ${{ github.workspace }}/ut_log/xpu_distributed_bmg/xpu_distributed_bmg_test.log
+        find ../ -type f -name "*.xml" -exec cp {} ${{ github.workspace }}/ut_log/ \;
+
     - name: p0
       shell: timeout 72000 bash -eo pipefail {0}
       if: ${{ inputs.ut_name == 'p0' }}
