update

diff --git a/.github/actions/linux-uttest/action.yml b/.github/actions/linux-uttest/action.yml
--- a/.github/actions/linux-uttest/action.yml
+++ b/.github/actions/linux-uttest/action.yml
@@ -102,19 +102,19 @@ runs:
         cp *.xml ${{ github.workspace }}/ut_log
         echo -e "File Path: cd pytorch/third_party/torch-xpu-ops/test/xpu" | tee -a ${{ github.workspace }}/ut_log/reproduce_op_ut.log
         echo -e "Reproduce Command: pytest -sv failed_case" | tee -a ${{ github.workspace }}/ut_log/reproduce_op_ut.log
-    - name: op_skipped
+    - name: skipped_ut
       shell: timeout 18000 bash -xe {0}
-      if: ${{ inputs.ut_name == 'op_skipped' }}
+      if: ${{ inputs.ut_name == 'skipped_ut' }}
       run: |
         export PYTORCH_TEST_WITH_SLOW=1
         export PYTORCH_ENABLE_XPU_FALLBACK=1
-        mkdir -p ut_log/op_skipped
+        mkdir -p ut_log/skipped_ut
         cd pytorch/third_party/torch-xpu-ops/test/xpu
-        python run_test_with_skip.py -k skipped \
-          2> ${{ github.workspace }}/ut_log/op_skipped/op_skipped_with_skip_test_error.log | \
-          tee ${{ github.workspace }}/ut_log/op_skipped/op_skipped_with_skip_test.log
-        echo -e "File Path: cd pytorch/third_party/torch-xpu-ops/test/xpu" | tee -a ${{ github.workspace }}/ut_log/reproduce_op_skipped.log
-        echo -e "Reproduce Command: pytest -sv failed_case" | tee -a ${{ github.workspace }}/ut_log/reproduce_op_skipped.log
+        python run_test_with_skip.py --test-cases skipped \
+          2> ${{ github.workspace }}/ut_log/skipped_ut/skipped_ut_with_skip_test_error.log | \
+          tee ${{ github.workspace }}/ut_log/skipped_ut/skipped_ut_with_skip_test.log
+        echo -e "File Path: cd pytorch/third_party/torch-xpu-ops/test/xpu" | tee -a ${{ github.workspace }}/ut_log/reproduce_skipped_ut.log
+        echo -e "Reproduce Command: pytest -sv failed_case" | tee -a ${{ github.workspace }}/ut_log/reproduce_skipped_ut.log
         cp *.xml ${{ github.workspace }}/ut_log
     - name: torch_xpu
       shell: timeout 3600 bash -xe {0}
@@ -193,7 +193,7 @@ runs:
       shell: timeout 180 bash -xe {0}
       run: |
         pip install junitparser
-        python ./.github/scripts/check-ut.py -k ${{ inputs.ut_name }} -i ${{ github.workspace }}/ut_log/*.xml >> $GITHUB_STEP_SUMMARY || true
+        python ./.github/scripts/check-ut.py -n ${{ inputs.ut_name }} -i ${{ github.workspace }}/ut_log/*.xml >> $GITHUB_STEP_SUMMARY || true
         # Check the failure logs
         if ls ${{ github.workspace }}/failures*.log 1> /dev/null 2>&1; then
           echo -e "Exist Failure logs"
