update log heck

diff --git a/.github/workflows/_linux_ut.yml b/.github/workflows/_linux_ut.yml
--- a/.github/workflows/_linux_ut.yml
+++ b/.github/workflows/_linux_ut.yml
@@ -122,93 +122,115 @@ jobs:
           python test/run_test.py --xpu 2>&1 | tee ${{ github.workspace }}/ut_log/Torch_XPU_python_UT_Test.log
 
       - name: UT Test Results Check
-        if: 0
         shell: bash
         run: |
           source /opt/intel/oneapi/compiler/latest/env/vars.sh
           source activate xpu_op_${ZE_AFFINITY_MASK}
-          cd ${{ github.workspace }}/ut_log
-          echo -e "========================================================================="
-          echo -e "XPU OP Examples UT Results Check"
-          echo -e "========================================================================="
-          grep "^FAILED" XPU_OP_op_example_Test.log | awk '{print $1}' > ./op_example_failed.log
-          grep "PASSED" XPU_OP_op_example_Test.log | awk '{print $1}' > ./op_example_passed.log
-          num_failed_op_example=$(cat ./op_example_failed.log | wc -l)
-          num_passed_op_example=$(cat ./op_example_passed.log | wc -l)
-          echo "num_failed_op_example: $num_failed_op_example" | tee -a ./ut_summary.log
-          echo "num_passed_op_example: $num_passed_op_example" | tee -a ./ut_summary.log
-
-          echo -e "========================================================================="
-          echo -e "XPU OP Extended UT Results Check"
-          echo -e "========================================================================="
-          grep "^FAILED" XPU_OP_op_extended_Test.log | awk '{print $1}' > ./op_extended_failed.log
-          grep "PASSED" XPU_OP_op_extended_Test.log | awk '{print $1}' > ./op_extended_passed.log
-          num_failed_op_extended=$(cat ./op_extended_failed.log | wc -l)
-          num_passed_op_extended=$(cat ./op_extended_passed.log | wc -l)
-          echo "num_failed_op_extended: $num_failed_op_extended" | tee -a ./ut_summary.log
-          echo "num_passed_op_extended: $num_passed_op_extended" | tee -a ./ut_summary.log
-
-          echo -e "========================================================================="
-          echo -e "XPU OP UT Results Check"
-          echo -e "========================================================================="
-          grep "^FAILED" XPU_OP_with_skip_UT_Test.log | awk '{print $1}' > ./op_ut_with_skip_failed.log
-          grep "^FAILED" XPU_OP_with_only_UT_Test.log | awk '{print $1}' > ./op_ut_with_only_failed.log
-          num_failed_with_skip=$(cat ./op_ut_with_skip_failed.log | wc -l)
-          num_failed_with_only=$(cat ./op_ut_with_only_failed.log | wc -l)
-          let num_failed_op_ut=num_failed_with_skip+num_failed_with_only
-          grep "PASSED" XPU_OP_with_skip_UT_Test.log | awk '{print $1}' > ./op_ut_with_skip_passedlog
-          grep "PASSED" XPU_OP_with_only_UT_Test.log | awk '{print $1}' > ./op_ut_with_only_passedlog
-          num_passed_with_skip=$(cat ./op_ut_with_skip_passed.log | wc -l)
-          num_passed_with_only=$(cat ./op_ut_with_only_passed.log | wc -l)
-          let num_passed_op_ut=num_passed_with_skip+num_passed_with_only
-          echo "num_failed_op_ut: $num_failed_op_ut" | tee -a ./ut_summary.log
-          echo "num_passed_op_ut: $num_passed_op_ut" | tee -a ./ut_summary.log
-
-          echo -e "========================================================================="
-          echo -e "Torch XPU UT Results Check"
-          echo -e "========================================================================="
-          echo "Pytorch XPU binary UT checking"
-          cd ${{ github.workspace }}
-          cd ../pytorch
-          TEST_REPORTS_DIR=$(pwd)/test/test-reports
-          for xpu_case in build/bin/*{xpu,sycl}*; do
-            if [[ "$xpu_case" != *"*"* && "$xpu_case" != *.so && "$xpu_case" != *.a ]]; then
-              case_name=$(basename "$xpu_case")
-              echo "Checking ${case_name} ..."
+          # check param
+            function contains() {
+                contains_status="echo 'Start $2 ...'"
+                {
+                  [[ $1 =~ (^|,)$2($|,) ]]
+                } || {
+                  echo "[Warning] $2 is not suppotted type! Skipped!"
+                  contains_status="continue"
+                }
+            }
+            set -xe
+            for ut_suite in $(echo ${{ inputs.ut_suite }} |sed 's/,/ /g')
+            do
+              contains "op_example,op_extended,op_ut,torch_xpu" $ut_suite
+              $contains_status
               cd ${{ github.workspace }}/ut_log
-              grep -E "FAILED" binary_UT_torch_xpu_${case_name}_Test.log | awk '{print $2}' > ./binary_UT_torch_xpu_${case_name}_failed.log
-              echo $(cat ./binary_UT_torch_xpu_${case_name}_failed.log | wc -l) | tee -a ./binary_UT_torch_xpufailed_summary.log
-              grep -E "PASSED|Pass" binary_UT_torch_xpu_${case_name}_Test.log | awk '{print $2}' > ./binary_UT_torch_xpu_${case_name}_passed.log
-              echo $(cat ./binary_UT_torch_xpu_${case_name}_passed.log | wc -l) | tee -a ./binary_torch_xpu_ut_passed_summary.log
-            fi
-          done
-          num_failed_binary_UT=$(awk '{sum += $1};END {print sum}' binary_UT_torch_xpu_failed_summary.log)
-          num_passed_binary_UT=$(awk '{sum += $1};END {print sum}' binary_UT_torch_xpu_passed_summary.log)
-          let num_failed_torch_xpu=num_failed_binary_UT
-          let num_passed_torch_xpu=num_passed_binary_UT
-          echo "num_failed_torch_xpu: $num_failed_torch_xpu" | tee -a ./ut_summary.log
-          echo "num_passed_torch_xpu: $num_passed_torch_xpu" | tee -a ./ut_summary.log
-          
-          if [[ $num_failed_op_example -gt 0 ]] && [[ $num_passed_op_example -lt 0 ]]; then
-            echo -e "[ERROR] Inductor UT test for XPU OP Examples failed number > 0"
-            exit 1
-          fi
+              if [[ ${ut_suite} == 'op_example' ]];then
+                echo -e "========================================================================="
+                echo -e "XPU OP Examples UT Results Check"
+                echo -e "========================================================================="
+                grep "^FAILED" XPU_OP_op_example_Test.log | awk '{print $1}' > ./op_example_failed.log
+                grep "PASSED" XPU_OP_op_example_Test.log | awk '{print $1}' > ./op_example_passed.log
+                num_failed_op_example=$(cat ./op_example_failed.log | wc -l)
+                num_passed_op_example=$(cat ./op_example_passed.log | wc -l)
+                echo "num_failed_op_example: $num_failed_op_example" | tee -a ./ut_summary.log
+                echo "num_passed_op_example: $num_passed_op_example" | tee -a ./ut_summary.log
+              fi
 
-          if [[ $num_failed_op_extended -gt 0 ]] && [[ $num_passed_op_extended -lt 0 ]]; then
-            echo -e "[ERROR] Inductor UT test for XPU OP Extended failed number > 0"
-            exit 1
-          fi
+              if [[ ${ut_suite} == 'op_extended' ]]; then
+                echo -e "========================================================================="
+                echo -e "XPU OP Extended UT Results Check"
+                echo -e "========================================================================="
+                grep "^FAILED" XPU_OP_op_extended_Test.log | awk '{print $1}' > ./op_extended_failed.log
+                grep "PASSED" XPU_OP_op_extended_Test.log | awk '{print $1}' > ./op_extended_passed.log
+                num_failed_op_extended=$(cat ./op_extended_failed.log | wc -l)
+                num_passed_op_extended=$(cat ./op_extended_passed.log | wc -l)
+                echo "num_failed_op_extended: $num_failed_op_extended" | tee -a ./ut_summary.log
+                echo "num_passed_op_extended: $num_passed_op_extended" | tee -a ./ut_summary.log
+              fi
 
-          if [[ $num_failed_op_ut -gt 0 ]] && [[ $num_passed_op_ut -lt 0 ]]; then
-            echo -e "[ERROR] Inductor UT test for XPU OP UT failed number > 0"
-            exit 1
-          fi
+              if [[ ${ut_suite} == 'op_ut' ]]; then
+                echo -e "========================================================================="
+                echo -e "XPU OP UT Results Check"
+                echo -e "========================================================================="
+                grep "^FAILED" XPU_OP_with_skip_UT_Test.log | awk '{print $1}' > ./op_ut_with_skip_failed.log
+                grep "^FAILED" XPU_OP_with_only_UT_Test.log | awk '{print $1}' > ./op_ut_with_only_failed.log
+                num_failed_with_skip=$(cat ./op_ut_with_skip_failed.log | wc -l)
+                num_failed_with_only=$(cat ./op_ut_with_only_failed.log | wc -l)
+                let num_failed_op_ut=num_failed_with_skip+num_failed_with_only
+                grep "PASSED" XPU_OP_with_skip_UT_Test.log | awk '{print $1}' > ./op_ut_with_skip_passedlog
+                grep "PASSED" XPU_OP_with_only_UT_Test.log | awk '{print $1}' > ./op_ut_with_only_passedlog
+                num_passed_with_skip=$(cat ./op_ut_with_skip_passed.log | wc -l)
+                num_passed_with_only=$(cat ./op_ut_with_only_passed.log | wc -l)
+                let num_passed_op_ut=num_passed_with_skip+num_passed_with_only
+                echo "num_failed_op_ut: $num_failed_op_ut" | tee -a ./ut_summary.log
+                echo "num_passed_op_ut: $num_passed_op_ut" | tee -a ./ut_summary.log
+              fi
 
-          if if [[ $num_failed_torch_xpu -gt 0 ]] && [[ $num_passed_torch_xpu -lt 0 ]]; then
-            echo -e "[ERROR] Inductor UT test for Torch XPU UT failed number > 0"
-            exit 1
-          fi
-          
+              if [[ ${ut_suite} == 'torch_xpu' ]]; then
+                echo -e "========================================================================="
+                echo -e "Torch XPU UT Results Check"
+                echo -e "========================================================================="
+                echo "Pytorch XPU binary UT checking"
+                cd ${{ github.workspace }}
+                cd ../pytorch
+                TEST_REPORTS_DIR=$(pwd)/test/test-reports
+                for xpu_case in build/bin/*{xpu,sycl}*; do
+                  if [[ "$xpu_case" != *"*"* && "$xpu_case" != *.so && "$xpu_case" != *.a ]]; then
+                    case_name=$(basename "$xpu_case")
+                    echo "Checking ${case_name} ..."
+                    cd ${{ github.workspace }}/ut_log
+                    grep -E "FAILED" binary_UT_torch_xpu_${case_name}_Test.log | awk '{print $2}' > ./binary_UT_torch_xpu_${case_name}_failed.log
+                    echo $(cat ./binary_UT_torch_xpu_${case_name}_failed.log | wc -l) | tee -a ./binary_UT_torch_xpufailed_summary.log
+                    grep -E "PASSED|Pass" binary_UT_torch_xpu_${case_name}_Test.log | awk '{print $2}' > ./binary_UT_torch_xpu_${case_name}_passed.log
+                    echo $(cat ./binary_UT_torch_xpu_${case_name}_passed.log | wc -l) | tee -a ./binary_torch_xpu_ut_passed_summary.log
+                  fi
+                done
+                num_failed_binary_UT=$(awk '{sum += $1};END {print sum}' binary_UT_torch_xpu_failed_summary.log)
+                num_passed_binary_UT=$(awk '{sum += $1};END {print sum}' binary_UT_torch_xpu_passed_summary.log)
+                let num_failed_torch_xpu=num_failed_binary_UT
+                let num_passed_torch_xpu=num_passed_binary_UT
+                echo "num_failed_torch_xpu: $num_failed_torch_xpu" | tee -a ./ut_summary.log
+                echo "num_passed_torch_xpu: $num_passed_torch_xpu" | tee -a ./ut_summary.log
+              fi
+              
+              if [[ -n $num_failed_op_example ]] && [[ $num_failed_op_example -gt 0 ]] && [[ $num_passed_op_example -lt 0 ]]; then
+                echo -e "[ERROR] Inductor UT test for XPU OP Examples failed number > 0"
+                exit 1
+              fi
+
+              if [[ -n $num_failed_op_extended ]] && [[ $num_failed_op_extended -gt 0 ]] && [[ $num_passed_op_extended -lt 0 ]]; then
+                echo -e "[ERROR] Inductor UT test for XPU OP Extended failed number > 0"
+                exit 1
+              fi
+
+              if [[ -n $num_failed_op_ut ]] && [[ $num_failed_op_ut -gt 0 ]] && [[ $num_passed_op_ut -lt 0 ]]; then
+                echo -e "[ERROR] Inductor UT test for XPU OP UT failed number > 0"
+                exit 1
+              fi
+
+              if [[ -n $num_failed_torch_xpu ]] && [[ $num_failed_torch_xpu -gt 0 ]] && [[ $num_passed_torch_xpu -lt 0 ]]; then
+                echo -e "[ERROR] Inductor UT test for Torch XPU UT failed number > 0"
+                exit 1
+              fi
+            done
       - name: Upload Inductor XPU UT Data
         if: always()
         uses: actions/upload-artifact@v4
