Use single HF cache location
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

diff --git a/.github/workflows/_linux_transformers.yml b/.github/workflows/_linux_transformers.yml
--- a/.github/workflows/_linux_transformers.yml
+++ b/.github/workflows/_linux_transformers.yml
@@ -44,6 +44,7 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 env:
+  #HF_HOME: ${{ github.workspace }}/.hf_home_of_transformers_test
   HF_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
   NEOReadDebugKeys: ${{ inputs.driver == 'rolling' && '1' || '0' }}
   DisableScratchPages: ${{ inputs.driver == 'rolling' && '1' || '0' }}
@@ -129,7 +130,7 @@ jobs:
             cmd: '--ignore=tests/utils/test_import_utils.py tests/utils'
             filter: 'not test_load_img_url_timeout'
     env:
-      HF_HOME: ${{ github.workspace }}/.hf_home_${{ matrix.test.test_case }}
+      #HF_HOME: ${{ github.workspace }}/.hf_home_${{ matrix.test.test_case }}
       PYTORCH_DEBUG_XPU_FALLBACK: '1'
       TRANSFORMERS_TEST_DEVICE_SPEC: 'spec.py'
     steps:
@@ -143,6 +144,19 @@ jobs:
           repository: huggingface/transformers
           ref: ${{ env.transformers }}
           path: transformers
+      - name: Prepare HF cache directory
+        run: |
+          echo "HF_HOME=$HOME/.hf_home_of_transformers_test" >> $GITHUB_ENV
+      - name: Report HF cache directory
+        run: |
+          if [ -d "$HF_HOME" ]; then
+            ls -al ${{ env.HF_HOME }}
+            du -sh ${{ env.HF_HOME }}
+          else
+            echo "HF cache directory does not exist"
+            echo "WARNING: Some tests might fail fetching content from the hub!"
+            echo "WARNING: Populate cache with test content!"
+          fi
       - name: Prepare OS environment
         run: |
           # as jobs might run in parallel on the same system, apt-get might
@@ -209,9 +223,6 @@ jobs:
           pip show torchaudio | grep Version | grep xpu
           pip show torchvision | grep Version | grep xpu
           python -c 'import torch; exit(not torch.xpu.is_available())'
-      - name: Clean HF home directory and cache
-        run: |
-          rm -rf ${{ env.HF_HOME }}
       - name: Run tests
         env:
           TEST_CASE: ${{matrix.test.test_case}}
@@ -219,7 +230,7 @@ jobs:
           source activate $CONDA_ENV_NAME
           cd transformers
           python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml \
-            --reruns 5 --reruns-delay 2 \
+            --reruns 2 --reruns-delay 2 \
             -k "${{ matrix.test.filter}}" ${{ matrix.test.cmd }} || true
       - name: Check for errors in tests
         run: |
@@ -235,8 +246,8 @@ jobs:
       - name: Clean up
         if: ${{ always() }}
         run: |
-          du -sh ${{ env.HF_HOME }} || true
-          rm -rf ${{ env.HF_HOME }}
+          #du -sh ${{ env.HF_HOME }} || true
+          #rm -rf ${{ env.HF_HOME }}
           if [ -n "$CONDA_ENV_NAME" ]; then
             conda remove --all -y -n $CONDA_ENV_NAME || rm -rf $(dirname ${CONDA_EXE})/../envs/$CONDA_ENV_NAME
           fi
