modify build

diff --git a/.github/workflows/_linux_build.yml b/.github/workflows/_linux_build.yml
--- a/.github/workflows/_linux_build.yml
+++ b/.github/workflows/_linux_build.yml
@@ -119,6 +119,10 @@ jobs:
             --TORCH_XPU_OPS_REPO="${TORCH_XPU_OPS_REPO}" \
             --TORCH_XPU_OPS_COMMIT="${TORCH_XPU_OPS_COMMIT}" \
             2>&1 |tee ${{ github.workspace }}/build_pytorch_${PYTORCH_COMMIT//\//-}.log
+          if [ ! -f "${{ github.workspace }}/torch-*.whl" ];then
+            echo "Build pytorch got failed"
+            exit 1
+          fi
       - name: Build Triton
         run: |
           cd ./pytorch
@@ -135,6 +139,10 @@ jobs:
           )"
           python .github/scripts/build_triton_wheel.py --device xpu --commit-hash ${TRITON_COMMIT_ID} --triton-version ${TRITON_VERSION_NAME} \
             2>&1 |tee ${{ github.workspace }}/build_triton_${TRITON_COMMIT_ID}.log
+          if [ ! -f "${{ github.workspace }}/pytorch_triton_xpu-*.whl" ];then
+            echo "Build triton got failed"
+            exit 1
+          fi
           pip install pytorch_triton_xpu-*.whl
           cp pytorch_triton_xpu-*.whl ${{ github.workspace }}
       - name: Build Torchvision and Torchaudio
@@ -148,11 +156,19 @@ jobs:
           git clone --single-branch -b main https://github.com/pytorch/vision.git xpu-vision
           cd xpu-vision && git checkout ${TORCHVISION_COMMIT_ID}
           python setup.py bdist_wheel 2>&1 |tee ${{ github.workspace }}/build_vision_${TRITON_COMMIT_ID}.log
+          if [ ! -f "dist/*.whl" ];then
+            echo "Build torchvision got failed"
+            exit 1
+          fi
           pip install dist/*.whl
           cp dist/*.whl ${{ github.workspace }}
           git clone --single-branch -b main https://github.com/pytorch/audio.git xpu-audio
           cd xpu-audio && git checkout ${TORCHAUDIO_COMMIT_ID}
           python setup.py bdist_wheel 2>&1 |tee ${{ github.workspace }}/build_audio_${TRITON_COMMIT_ID}.log
+          if [ ! -f "dist/*.whl" ];then
+            echo "Build torchaudio got failed"
+            exit 1
+          fi
           pip install dist/*.whl
           cp dist/*.whl ${{ github.workspace }}
       - name: Torch Config
