modify triton build

diff --git a/.github/workflows/_linux_build.yml b/.github/workflows/_linux_build.yml
--- a/.github/workflows/_linux_build.yml
+++ b/.github/workflows/_linux_build.yml
@@ -153,29 +153,41 @@ jobs:
           cp dist/*.whl ${{ github.workspace }}
       - name: Build Triton
         run: |
-          # gcc 13
-          dnf install -y gcc-toolset-13-gcc-c++ zlib-devel
-          source /opt/rh/gcc-toolset-13/enable
           cd ./pytorch
-          pip install cmake ninja pybind11
           rm -rf pytorch_triton_xpu-*.whl
           if [ "${{ inputs.triton }}" != "pinned" ];then
             TRITON_COMMIT_ID="${{ inputs.triton }}"
           else
             TRITON_COMMIT_ID="$(cat .ci/docker/ci_commit_pins/triton-xpu.txt)"
           fi
-          TRITON_VERSION_NAME="$(
-            curl -sSL https://raw.githubusercontent.com/intel/intel-xpu-backend-for-triton/${TRITON_COMMIT_ID}/python/triton/__init__.py 2>&1 |\
-                    grep '__version__' |head -n 1 |awk -F "'" '{print $2}'
-          )"
-          python .github/scripts/build_triton_wheel.py --device xpu --commit-hash ${TRITON_COMMIT_ID} --triton-version ${TRITON_VERSION_NAME} \
-            2>&1 |tee ${{ github.workspace }}/build_triton_${TRITON_COMMIT_ID}.log
-          if [ $(ls |grep -c "pytorch_triton_xpu-.*.whl") -eq 0 ];then
-            echo "Build triton got failed"
-            exit 1
+          built_version="$(pip index versions --index-url https://download.pytorch.org/whl/nightly/xpu --pre \
+                  pytorch-triton-xpu 2> /dev/null |awk -F '[ |,]' -v p="$(echo ${TRITON_COMMIT_ID} |awk '{print substr($1,0,7)}')" 'BEGIN{
+            v = "None";
+          }{
+            for (i=1;i<=NF;i++) {if ($i ~ p) {v = $i;}};
+          }END{
+            printf("%s", v);
+          }')"
+          if [ "${built_version}" != "None" ];then
+            pip download --index-url https://download.pytorch.org/whl/nightly/xpu --pre pytorch-triton-xpu==${built_version} --dest ${{ github.workspace }}/
+          else
+            TRITON_VERSION_NAME="$(
+              curl -sSL https://raw.githubusercontent.com/intel/intel-xpu-backend-for-triton/${TRITON_COMMIT_ID}/python/triton/__init__.py 2>&1 |\
+                      grep '__version__' |head -n 1 |awk -F "'" '{print $2}'
+            )"
+            # gcc 13
+            dnf install -y gcc-toolset-13-gcc-c++ zlib-devel
+            source /opt/rh/gcc-toolset-13/enable
+            pip install cmake ninja pybind11
+            python .github/scripts/build_triton_wheel.py --device xpu --commit-hash ${TRITON_COMMIT_ID} --triton-version ${TRITON_VERSION_NAME} \
+              2>&1 |tee ${{ github.workspace }}/build_triton_${TRITON_COMMIT_ID}.log
+            if [ $(ls |grep -c "pytorch_triton_xpu-.*.whl") -eq 0 ];then
+              echo "Build triton got failed"
+              exit 1
+            fi
+            pip install pytorch_triton_xpu-*.whl
+            cp pytorch_triton_xpu-*.whl ${{ github.workspace }}
           fi
-          pip install pytorch_triton_xpu-*.whl
-          cp pytorch_triton_xpu-*.whl ${{ github.workspace }}
       - name: Torch Config
         run: |
           printenv
