enhance the workflow

diff --git a/.github/workflows/_linux_ut.yml b/.github/workflows/_linux_ut.yml
--- a/.github/workflows/_linux_ut.yml
+++ b/.github/workflows/_linux_ut.yml
@@ -138,189 +138,28 @@ jobs:
           - name: 'torch_xpu_1'
             condition: ${{ contains(inputs.ut, 'torch_xpu') }}
             directory: '../pytorch'
-            command_script: |
-              export PYTORCH_TEST_WITH_SLOW=1
-              export PYTORCH_TESTING_DEVICE_ONLY_FOR="xpu"
-              echo -e \
-              "test_codecache.py\n" \
-              "test_kernel_benchmark.py\n" \
-              "test_max_autotune.py\n" \
-              "test_mkldnn_pattern_matcher.py\n" \
-              "test_triton_kernels.py\n" \
-              "test_torchinductor.py\n" \
-              "test_compiled_optimizers.py\n" \
-              "test_compiled_autograd.py\n" \
-              "test_compile_subprocess.py" \
-              > test_files_1.txt
-              for line in $(cat test_files_1.txt)
-              do
-                echo "=== Starting test: ${line} ==="
-                start=$(date +%s)
-                if [[ "${{ inputs.keep_going }}" == "true" ]];then
-                  python test/run_test.py --keep-going --xpu --include inductor/${line} 2>$GITHUB_WORKSPACE/ut_log/torch_xpu_1/torch_xpu_${line}_test_error.log | \
-                    tee $GITHUB_WORKSPACE/ut_log/torch_xpu_1/torch_xpu_${line}_test.log
-                else
-                  python test/run_test.py --xpu --include inductor/${line} 2>$GITHUB_WORKSPACE/ut_log/torch_xpu_1/torch_xpu_${line}_test_error.log | \
-                    tee $GITHUB_WORKSPACE/ut_log/torch_xpu_1/torch_xpu_${line}_test.log
-                fi
-                end=$(date +%s)
-                echo -e "${line} duration: $((end - start))s"
-                echo "=== Finished test: ${line} ==="
-              done
-              cp -r test/test-reports/*.log "$GITHUB_WORKSPACE/ut_log/torch_xpu_1/"
-              function read_dir(){
-                for file in `ls $1`
-                do
-                  if [ -d $1"/"$file ]
-                  then
-                    cp $1"/"$file"/"*.xml $GITHUB_WORKSPACE/ut_log/
-                  else
-                    echo "[Warning] $file has no xml"
-                  fi
-                done
-              }
-              read_dir "test/test-reports/python-pytest"
-              function rename_inductor_files() {
-                  local target_dir="${1:-.}"
-                  
-                  if [ ! -d "$target_dir" ]; then
-                      echo "Error: Directory '$target_dir' does not exist" >&2
-                      return 1
-                  fi
-
-                  find "$target_dir" -name 'inductor.*' -exec bash -c '
-                      for file; do
-                          newfile=$(echo "$file" | sed "s/inductor\./inductor_/")
-                          if [ "$file" != "$newfile" ]; then
-                              echo "Renaming: $file -> $newfile"
-                              mv -v "$file" "$newfile"
-                          fi
-                      done
-                  ' bash {} +
-              }
-              rename_inductor_files "$GITHUB_WORKSPACE/ut_log/torch_xpu_1"
-              rename_inductor_files "$GITHUB_WORKSPACE/ut_log/"
-            log_prefix: 'torch_xpu_1'
+            test_files: |
+              test_codecache.py
+              test_kernel_benchmark.py
+              test_max_autotune.py
+              test_mkldnn_pattern_matcher.py
+              test_triton_kernels.py
+              test_torchinductor.py
+              test_compiled_optimizers.py
+              test_compiled_autograd.py
+              test_compile_subprocess.py
             additional_steps: |
               pip install pytest pytest-timeout
           - name: 'torch_xpu_2'
             condition: ${{ contains(inputs.ut, 'torch_xpu') }}
             directory: '../pytorch'
-            command_script: |
-              export PYTORCH_TEST_WITH_SLOW=1
-              export PYTORCH_TESTING_DEVICE_ONLY_FOR="xpu"
-              echo -e \
-              "test_torchinductor_opinfo.py" \
-              > test_files_2.txt
-              for line in $(cat test_files_2.txt)
-              do
-                echo "=== Starting test: ${line} ==="
-                start=$(date +%s)
-                if [[ "${{ inputs.keep_going }}" == "true" ]];then
-                  python test/run_test.py --keep-going --xpu --include inductor/${line} 2>$GITHUB_WORKSPACE/ut_log/torch_xpu_2/torch_xpu_${line}_test_error.log | \
-                    tee $GITHUB_WORKSPACE/ut_log/torch_xpu_2/torch_xpu_${line}_test.log
-                else
-                  python test/run_test.py --xpu --include inductor/${line} 2>$GITHUB_WORKSPACE/ut_log/torch_xpu_2/torch_xpu_${line}_test_error.log | \
-                    tee $GITHUB_WORKSPACE/ut_log/torch_xpu_2/torch_xpu_${line}_test.log
-                fi
-                end=$(date +%s)
-                echo -e "${line} duration: $((end - start))s"
-                echo "=== Finished test: ${line} ==="
-              done
-              cp -r test/test-reports/*.log "$GITHUB_WORKSPACE/ut_log/torch_xpu_2/"
-              function read_dir(){
-                for file in `ls $1`
-                do
-                  if [ -d $1"/"$file ]
-                  then
-                    cp $1"/"$file"/"*.xml $GITHUB_WORKSPACE/ut_log/
-                  else
-                    echo "[Warning] $file has no xml"
-                  fi
-                done
-              }
-              read_dir "test/test-reports/python-pytest"
-              function rename_inductor_files() {
-                  local target_dir="${1:-.}"
-                  
-                  if [ ! -d "$target_dir" ]; then
-                      echo "Error: Directory '$target_dir' does not exist" >&2
-                      return 1
-                  fi
-
-                  find "$target_dir" -name 'inductor.*' -exec bash -c '
-                      for file; do
-                          newfile=$(echo "$file" | sed "s/inductor\./inductor_/")
-                          if [ "$file" != "$newfile" ]; then
-                              echo "Renaming: $file -> $newfile"
-                              mv -v "$file" "$newfile"
-                          fi
-                      done
-                  ' bash {} +
-              }
-              rename_inductor_files "$GITHUB_WORKSPACE/ut_log/torch_xpu_2"
-              rename_inductor_files "$GITHUB_WORKSPACE/ut_log/"
-            log_prefix: 'torch_xpu_2'
+            test_files: "test_torchinductor_opinfo.py"
             additional_steps: |
               pip install pytest pytest-timeout
           - name: 'torch_xpu_3'
             condition: ${{ contains(inputs.ut, 'torch_xpu') }}
             directory: '../pytorch'
-            command_script: |
-              export PYTORCH_TEST_WITH_SLOW=1
-              export PYTORCH_TESTING_DEVICE_ONLY_FOR="xpu"
-              echo -e \
-              "test_aot_inductor.py" \
-              > test_files_3.txt
-              for line in $(cat test_files_3.txt)
-              do
-                echo "=== Starting test: ${line} ==="
-                start=$(date +%s)
-                if [[ "${{ inputs.keep_going }}" == "true" ]];then
-                  python test/run_test.py --keep-going --xpu --include inductor/${line} 2>$GITHUB_WORKSPACE/ut_log/torch_xpu_3/torch_xpu_${line}_test_error.log | \
-                    tee $GITHUB_WORKSPACE/ut_log/torch_xpu_3/torch_xpu_${line}_test.log
-                else
-                  python test/run_test.py --xpu --include inductor/${line} 2>$GITHUB_WORKSPACE/ut_log/torch_xpu_3/torch_xpu_${line}_test_error.log | \
-                    tee $GITHUB_WORKSPACE/ut_log/torch_xpu_3/torch_xpu_${line}_test.log
-                fi
-                end=$(date +%s)
-                echo -e "${line} duration: $((end - start))s"
-                echo "=== Finished test: ${line} ==="
-              done
-              cp -r test/test-reports/*.log "$GITHUB_WORKSPACE/ut_log/torch_xpu_3/"
-              function read_dir(){
-                for file in `ls $1`
-                do
-                  if [ -d $1"/"$file ]
-                  then
-                    cp $1"/"$file"/"*.xml $GITHUB_WORKSPACE/ut_log/
-                  else
-                    echo "[Warning] $file has no xml"
-                  fi
-                done
-              }
-              read_dir "test/test-reports/python-pytest"
-              function rename_inductor_files() {
-                  local target_dir="${1:-.}"
-                  
-                  if [ ! -d "$target_dir" ]; then
-                      echo "Error: Directory '$target_dir' does not exist" >&2
-                      return 1
-                  fi
-
-                  find "$target_dir" -name 'inductor.*' -exec bash -c '
-                      for file; do
-                          newfile=$(echo "$file" | sed "s/inductor\./inductor_/")
-                          if [ "$file" != "$newfile" ]; then
-                              echo "Renaming: $file -> $newfile"
-                              mv -v "$file" "$newfile"
-                          fi
-                      done
-                  ' bash {} +
-              }
-              rename_inductor_files "$GITHUB_WORKSPACE/ut_log/torch_xpu_3"
-              rename_inductor_files "$GITHUB_WORKSPACE/ut_log/"
-            log_prefix: 'torch_xpu_3'
+            test_files: "test_aot_inductor.py"
             additional_steps: |
               pip install pytest pytest-timeout
           - name: 'xpu_profiling'
@@ -456,11 +295,58 @@ jobs:
 
           cd ${{ matrix.test.directory }}
 
-          if [[ "${{ matrix.test.name }}" =~ ^(op_ut|xpu_profiling|torch_xpu_[123])$ ]]; then
+          if [[ "${{ matrix.test.name }}" =~ ^(op_ut|xpu_profiling)$ ]]; then
             bash << "SCRIPT"
             set -e
             ${{ matrix.test.command_script }}
           SCRIPT
+          elif [[ "${{ matrix.test.name }}" =~ ^(torch_xpu_[123])$ ]]; then
+            keep_going_flag=""
+            [[ "${{ inputs.keep_going }}" == "true" ]] && keep_going_flag="--keep-going"
+            export PYTORCH_TEST_WITH_SLOW=1
+            export PYTORCH_TESTING_DEVICE_ONLY_FOR="xpu"
+            echo -e "${{ matrix.test_files }}" > test_files.txt
+            for line in $(cat test_files.txt)
+            do
+              echo "=== Starting test: ${line} ==="
+              start=$(date +%s)
+              python test/run_test.py $keep_going_flag --xpu --include inductor/${line} 2>${{ github.workspace }}/ut_log/${{ matrix.test.name }}/torch_xpu_${line}_test_error.log | \
+                tee ${{ github.workspace }}/ut_log/${{ matrix.test.name }}/torch_xpu_${line}_test.log
+              end=$(date +%s)
+              echo -e "${line} duration: $((end - start))s"
+              echo "=== Finished test: ${line} ==="
+            done
+            cp -r test/test-reports/*.log "${{ github.workspace }}/ut_log/${{ matrix.test.name }}/"
+            function read_dir(){
+              for file in `ls $1`
+              do
+                if [ -d $1"/"$file ]
+                then
+                  cp $1"/"$file"/"*.xml ${{ github.workspace }}/ut_log/
+                else
+                  echo "[Warning] $file has no xml"
+                fi
+              done
+            }
+            read_dir "test/test-reports/python-pytest"
+            function rename_inductor_files() {
+                local target_dir="${1:-.}"
+                if [ ! -d "$target_dir" ]; then
+                    echo "Error: Directory '$target_dir' does not exist" >&2
+                    return 1
+                fi
+                find "$target_dir" -name 'inductor.*' -exec bash -c '
+                    for file; do
+                        newfile=$(echo "$file" | sed "s/inductor\./inductor_/")
+                        if [ "$file" != "$newfile" ]; then
+                            echo "Renaming: $file -> $newfile"
+                            mv -v "$file" "$newfile"
+                        fi
+                    done
+                ' bash {} +
+            }
+            rename_inductor_files "${{ github.workspace }}/ut_log/${{ matrix.test.name }}"
+            rename_inductor_files "${{ github.workspace }}/ut_log/"
           else
             ${{ matrix.test.command }} \
               2>${{ github.workspace }}/ut_log/${{ matrix.test.name }}/${{ matrix.test.log_prefix }}_test_error.log | \
