set timeout exit

diff --git a/.github/workflows/_linux_ut.yml b/.github/workflows/_linux_ut.yml
--- a/.github/workflows/_linux_ut.yml
+++ b/.github/workflows/_linux_ut.yml
@@ -286,6 +286,12 @@ jobs:
               2>${{ github.workspace }}/ut_log/${{ matrix.test.name }}/${{ matrix.test.log_prefix }}_test_error.log | \
               tee ${{ github.workspace }}/ut_log/${{ matrix.test.name }}/${{ matrix.test.log_prefix }}_test.log
             ${{ matrix.test.xml_post_processing || '' }}
+            EXIT_CODE=$?
+            echo "Pytest Exit Code: $EXIT_CODE"
+            if [ $EXIT_CODE -eq 124 ]; then
+              echo "Error: pytest timed out"
+              exit 1
+            fi
           fi
       - name: UT Test Results Summary
         if: ${{ matrix.test.condition }}
