ci: update Transformers to v4.49.0
Changes:
* Benchmarking scripts are pruned from Transformers by v4.49.0 due to
  deprecation. So we don't need to test them anymore.
* Some cuda specific tests were generalized to cover non-cuda devices
  which uncovered some issues.
* Some new tests were added which fail for both cuda and xpu.
* Few regressions due to changes on Transformers side

Fixed tests:
* https://github.com/huggingface/transformers/commit/b912f5ee438a1644247da13d789166ec77bb2304
  * `tests/models/git/test_modeling_git.py::GitModelTest::test_inputs_embeds_matches_input_ids`
* https://github.com/huggingface/transformers/commit/b5aaf875090388e2bbdbf2d8641ed7967365f435
  * `tests/pipelines/test_pipelines_video_classification.py::VideoClassificationPipelineTests::test_small_model_pt`
  * `tests/test_pipeline_mixin.py::VideoClassificationPipelineTests::test_small_model_pt`
* https://github.com/huggingface/transformers/commit/42c8ccfd4c466eedabc5e30ac34f242e2c9f9455
  * `tests/generation/test_utils.py::GenerationIntegrationTests::test_generated_length_assisted_generation`
* https://github.com/huggingface/transformers/commit/9fd123ac31b8597c5004be7986547914d5302069
  * `test_model_parallelization`
  * `test_model_parallel_equal_results`

Commits which added new tests (or enabled previously skipped tests) which fail:
* https://github.com/huggingface/transformers/commit/23d782ead2fceec3e197c57de70489ccfc3bd0ee
  * `tests/pipelines/test_pipelines_text_generation.py::TextGenerationPipelineTests::test_return_dict_in_generate`
  * `tests/test_pipeline_mixin.py::TextGenerationPipelineTests::test_return_dict_in_generate`
* https://github.com/huggingface/transformers/commit/2fa876d2d824123b80ced9d689f75a153731769b
  * `test_cpu_offload` (some of)
  * `test_disk_offload_bin` (some of)
  * `test_disk_offload_safetensors` (some of)
  * `tests/pipelines/test_pipelines_text_generation.py::TextGenerationPipelineTests::test_small_model_pt_bloom_accelerate`
* https://github.com/huggingface/transformers/commit/be2ac0916a7902e1683d708805270142257a254a
  * `tests/models/paligemma/test_modeling_paligemma.py::PaliGemmaForConditionalGenerationModelTest::test_generate_compilation_all_outputs`
  * `tests/models/paligemma2/test_modeling_paligemma2.py::PaliGemma2ForConditionalGenerationModelTest::test_generate_compilation_all_outputs`
* https://github.com/huggingface/transformers/issues/36340
  * `tests/pipelines/test_pipelines_audio_classification.py::AudioClassificationPipelineTests::test_small_model_pt_fp16`
* https://github.com/huggingface/transformers/commit/1fae54c7216e144b426e753400abdc1299d4fc74
  * `tests/trainer/test_trainer.py::TrainerIntegrationPrerunTest::test_gradient_accumulation_loss_alignment_with_model_loss`
* https://github.com/huggingface/transformers/commit/15ec971b8ec999c6a511debe04ba32c115fb7413
  * `tests/models/qwen2_5_vl/test_processor_qwen2_5_vl.py::Qwen2_5_VLProcessorTest::test_chat_template_video_custom_sampling`
  * `tests/models/qwen2_5_vl/test_processor_qwen2_5_vl.py::Qwen2_5_VLProcessorTest::test_chat_template_video_special_processing`

Regressions:
* https://github.com/huggingface/transformers/commit/365fecb4d0b6c87f20b93561e11c3d4c77938012
  * `tests/generation/test_utils.py::GenerationIntegrationTests::test_encoder_decoder_generate_attention_mask`
* https://github.com/huggingface/transformers/commit/da334bcfa8ff7feb85138ce90ca7340e4fc6e704
  * `tests/generation/test_utils.py::GenerationIntegrationTests::test_generate_input_features_as_encoder_kwarg`
* https://github.com/huggingface/transformers/commit/bcfc9d795e1330faaa8b39ffa18732f8b40fe7c0
  * `tests/models/llava/test_modeling_llava.py::LlavaForConditionalGenerationModelTest::test_config`
* https://github.com/huggingface/transformers/issues/36267
  * `tests/utils/test_import_utils.py`
* https://github.com/huggingface/transformers/issues/36267
  * `tests/models/marian/test_modeling_marian.py`

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

diff --git a/.github/workflows/_linux_transformers.yml b/.github/workflows/_linux_transformers.yml
--- a/.github/workflows/_linux_transformers.yml
+++ b/.github/workflows/_linux_transformers.yml
@@ -41,7 +41,7 @@ on:
       transformers:
         required: false
         type: string
-        default: 'v4.47.0'
+        default: 'v4.49.0'
         description: Transformers version
 
 permissions: read-all
@@ -56,7 +56,8 @@ jobs:
       DisableScratchPages: ${{ inputs.driver == 'rolling' && '1' || '0' }}
       python: ${{ inputs.python != '' && inputs.python || '3.10' }}
       pytorch: ${{ inputs.pytorch != '' && inputs.pytorch || 'nightly' }}
-      transformers: ${{ inputs.transformers != '' && inputs.transformers || 'v4.47.0' }}
+      transformers: ${{ inputs.transformers != '' && inputs.transformers || 'v4.49.0' }}
+      PYTEST_TIMEOUT: 600
       PYTORCH_DEBUG_XPU_FALLBACK: '1'
       TRANSFORMERS_TEST_DEVICE_SPEC: 'spec.py'
     steps:
@@ -144,7 +145,11 @@ jobs:
         run: |
           source activate $CONDA_ENV_NAME
           cd transformers
-          python3 -m pytest --timeout 600 -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml -k backbone tests || \
+          # Excluding tests due to:
+          # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
+          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml \
+            --ignore=tests/models/marian/test_modeling_marian.py \
+            -k backbone tests || \
             (echo "FAILED_CASES=$FAILED_CASES,$TEST_CASE" >> $GITHUB_ENV)
       - name: Run tests/*.py
         env:
@@ -152,14 +157,7 @@ jobs:
         run: |
           source activate $CONDA_ENV_NAME
           cd transformers
-          python3 -m pytest --timeout 600 -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/*.py || true
-      - name: Run tests/benchmark
-        env:
-          TEST_CASE: 'tests_benchmark'
-        run: |
-          source activate $CONDA_ENV_NAME
-          cd transformers
-          python3 -m pytest --timeout 600 -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/benchmark || true
+          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/*.py || true
       - name: Run tests/generation
         env:
           TEST_CASE: 'tests_generation'
@@ -169,7 +167,7 @@ jobs:
           # Excluding tests due to:
           # * torch.distributed.* not yet supported by XPU
           pattern="not TestFSDPGeneration"
-          python3 -m pytest --timeout 600 -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/generation -k "$pattern" || true
+          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/generation -k "$pattern" || true
       - name: Run tests/models
         env:
           TEST_CASE: 'tests_models'
@@ -177,14 +175,14 @@ jobs:
           source activate $CONDA_ENV_NAME
           cd transformers
           # Excluding tests due to:
-          # * https://github.com/huggingface/transformers/issues/35252 (CUDA specific tests)
           # * https://github.com/pytorch/pytorch/issues/140965 (aten::_linalg_eigvals)
+          # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
           pattern=" \
-            not test_model_parallelization and \
-            not test_model_parallel_equal_results and \
             not test_resize_embeddings_untied and \
             not test_resize_tokens_embeddings"
-          python3 -m pytest --timeout 600 -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/models -k "$pattern" || true
+          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml \
+            -k "$pattern" --ignore=tests/models/marian/test_modeling_marian.py \
+            tests/models || true
       - name: Run tests/pipelines
         env:
           TEST_CASE: 'tests_pipelines'
@@ -193,7 +191,7 @@ jobs:
           cd transformers
           # Some tests are known to fail w/o clear pattern
           # TODO: drop ||true after triage and fixes
-          python3 -m pytest --timeout 600 -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/pipelines || true
+          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/pipelines || true
       - name: Run tests/trainer
         env:
           TEST_CASE: 'tests_trainer'
@@ -208,7 +206,7 @@ jobs:
             not TestTrainerDistributed and \
             not TestTrainerDistributedXPU and \
             not TestFSDPTrainer"
-          python3 -m pytest --timeout 600 -rsf --make-reports=$TEST_CASE tests/trainer --junit-xml=reports/$TEST_CASE.xml -k "$pattern" || \
+          python3 -m pytest -rsf --make-reports=$TEST_CASE tests/trainer --junit-xml=reports/$TEST_CASE.xml -k "$pattern" || \
             (echo "FAILED_CASES=$FAILED_CASES,$TEST_CASE" >> $GITHUB_ENV)
       - name: Run tests/utils
         env:
@@ -219,8 +217,11 @@ jobs:
           # Excluding tests due to:
           # * Network proxy connection issue, reason unknown
           pattern="not test_load_img_url_timeout"
-          python3 -m pytest --timeout 600 -rsf --make-reports=$TEST_CASE tests/utils --junit-xml=reports/$TEST_CASE.xml -k "$pattern" || \
-            (echo "FAILED_CASES=$FAILED_CASES,$TEST_CASE" >> $GITHUB_ENV)
+          # 'tests/utils/test_import_utils.py' invalidates state of the test engine causing
+          # next tests to fail. See: https://github.com/huggingface/transformers/issues/36267
+          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml \
+            -k "$pattern" --ignore=tests/utils/test_import_utils.py \
+            tests/utils || (echo "FAILED_CASES=$FAILED_CASES,$TEST_CASE" >> $GITHUB_ENV)
       - name: Check for errors in tests
         run: |
           FAILED_CASES=$(echo $FAILED_CASES | sed 's/^,//')
