ci: add trainer transformer tests
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

diff --git a/.github/workflows/_linux_transformers.yml b/.github/workflows/_linux_transformers.yml
--- a/.github/workflows/_linux_transformers.yml
+++ b/.github/workflows/_linux_transformers.yml
@@ -138,6 +138,32 @@ jobs:
             not TestTrainerDistributedXPU and \
             not TestFSDPTrainer"
           python3 -m pytest -rsf --make-reports=tests_trainer tests/trainer -k "$pattern"
+      - name: Run XPU pipelines tests
+        run: |
+          source activate huggingface_transformers_test
+          cd transformers
+          # Excluding tests due to:
+          # * Some ray tests hang, reason unknown
+          # * torch.distributed.* not yet supported by XPU
+          python3 -m pytest -rsf --make-reports=tests_pipelines tests/pipelines || true
+      - name: Check for expected results
+        run: |
+          function parse_stat() {
+            stat=$(cat $1 | grep $2 | sed "s/.* \([0-9]*\) $2.*/\1/")
+            if [ -n "$stat" ]; then echo $stat; else echo "0"; fi
+          }
+          echo "### Results" >> $GITHUB_STEP_SUMMARY
+          echo "| Test group | Errors | Failed | Passed | Skipped |" >> $GITHUB_STEP_SUMMARY
+          echo "| --- | --- | --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
+          for stat in $(find reports -name stats.txt); do
+            test_group=$(echo $stat | cut -f 2 -d/)
+            failed=$(parse_stat $stat failed)
+            passed=$(parse_stat $stat passed)
+            skipped=$(parse_stat $stat skipped)
+            warnings=$(parse_stat $stat warnings)
+            errors=$(parse_stat $stat errors)
+            echo "| $test_group | $errors | $failed | $passed | $skiped |" >> $GITHUB_STEP_SUMMARY
+          done
       - name: Upload Test log
         if: ${{ ! cancelled() }}
         uses: actions/upload-artifact@v4
