ci: use matrix jobs to test transformers
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

diff --git a/.github/workflows/_linux_transformers.yml b/.github/workflows/_linux_transformers.yml
--- a/.github/workflows/_linux_transformers.yml
+++ b/.github/workflows/_linux_transformers.yml
@@ -13,11 +13,6 @@ on:
       - '.github/workflows/_linux_transformers.yml'
   workflow_dispatch:
     inputs:
-      pytorch:
-        required: false
-        type: string
-        default: 'nightly'
-        description: Pytorch branch/commit
       python:
         required: false
         type: string
@@ -45,19 +40,96 @@ on:
         description: Transformers version
 
 permissions: read-all
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
+env:
+  HF_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
+  NEOReadDebugKeys: ${{ inputs.driver == 'rolling' && '1' || '0' }}
+  DisableScratchPages: ${{ inputs.driver == 'rolling' && '1' || '0' }}
+  python: ${{ inputs.python != '' && inputs.python || '3.10' }}
+  transformers: ${{ inputs.transformers != '' && inputs.transformers || 'v4.49.0' }}
+  PACKAGES: |
+    espeak-ng
+    git-lfs
+    pkg-config
+    libavcodec-dev
+    libavdevice-dev
+    libavfilter-dev
+    libavformat-dev
+    libavutil-dev
+    libswresample-dev
+    libswscale-dev
+  PYTEST_TIMEOUT: 600
+  TORCH_INDEX: '--pre --index-url https://download.pytorch.org/whl/nightly/xpu'
 
 jobs:
-  Torch-XPU-Transformers-Tests:
+  prepare:
     runs-on: ${{ inputs.runner != '' && inputs.runner || 'linux.idc.xpu' }}
+    outputs:
+      torch: ${{ steps.getver.outputs.torch }}
+      torchvision: ${{ steps.getver.outputs.torchvision }}
+      torchaudio: ${{ steps.getver.outputs.torchaudio }}
+    steps:
+      - id: getver
+        run: |
+          torch=$(pip index versions torch $TORCH_INDEX | grep torch | sed -E 's/.*\((.*)\)/\1/')
+          torchvision=$(pip index versions torchvision $TORCH_INDEX | grep torch | sed -E 's/.*\((.*)\)/\1/')
+          torchaudio=$(pip index versions torchaudio $TORCH_INDEX | grep torch | sed -E 's/.*\((.*)\)/\1/')
+          echo "torch=$torch" | tee -a "$GITHUB_OUTPUT"
+          echo "torchvision=$torchvision" | tee -a "$GITHUB_OUTPUT"
+          echo "torchaudio=$torchaudio" | tee -a "$GITHUB_OUTPUT"
+
+  tests:
+    needs: prepare
+    runs-on: ${{ inputs.runner != '' && inputs.runner || 'linux.idc.xpu' }}
+    strategy:
+      fail-fast: false
+      matrix:
+        test:
+          # Excluding tests due to:
+          # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
+          - test_case: 'tests_backbone'
+            cmd: '--ignore=tests/models/marian/test_modeling_marian.py -k backbone tests'
+          - test_case: "tests_py"
+            cmd: "tests/*.py"
+          # Excluding tests due to:
+          # * torch.distributed.* not yet supported by XPU
+          - test_case: 'tests_generation'
+            cmd: 'tests/generation'
+            filter: 'not TestFSDPGeneration'
+          # Excluding tests due to:
+          # * https://github.com/pytorch/pytorch/issues/140965 (aten::_linalg_eigvals)
+          # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
+          - test_case: 'tests_models_0'
+            cmd: 'tests/models --num-shards 4 --shard-id 0 --ignore=tests/models/marian/test_modeling_marian.py'
+            filter: 'not test_resize_embeddings_untied and not test_resize_tokens_embeddings'
+          - test_case: 'tests_models_1'
+            cmd: 'tests/models --num-shards 4 --shard-id 1 --ignore=tests/models/marian/test_modeling_marian.py'
+            filter: 'not test_resize_embeddings_untied and not test_resize_tokens_embeddings'
+          - test_case: 'tests_models_2'
+            cmd: 'tests/models --num-shards 4 --shard-id 2 --ignore=tests/models/marian/test_modeling_marian.py'
+            filter: 'not test_resize_embeddings_untied and not test_resize_tokens_embeddings'
+          - test_case: 'tests_models_3'
+            cmd: 'tests/models --num-shards 4 --shard-id 3 --ignore=tests/models/marian/test_modeling_marian.py'
+            filter: 'not test_resize_embeddings_untied and not test_resize_tokens_embeddings'
+          - test_case: 'tests_pipelines'
+            cmd: 'tests/pipelines'
+          # Excluding tests due to:
+          # * Some ray tests hang, reason unknown
+          # * torch.distributed.* not yet supported by XPU
+          - test_case: 'tests_trainer'
+            cmd: 'tests/trainer'
+            filter: 'not ray and not TestTrainerDistributed and not TestTrainerDistributedXPU and not TestFSDPTrainer'
+          # Excluding tests due to:
+          # * Network proxy connection issue, reason unknown
+          # *'tests/utils/test_import_utils.py' invalidates state of the test engine causing
+          #   next tests to fail. See: https://github.com/huggingface/transformers/issues/36267
+          - test_case: 'tests_utils'
+            cmd: '--ignore=tests/utils/test_import_utils.py tests/utils'
+            filter: 'not test_load_img_url_timeout'
     env:
-      HF_HOME: ${{ github.workspace }}/.hf_home
-      HF_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
-      NEOReadDebugKeys: ${{ inputs.driver == 'rolling' && '1' || '0' }}
-      DisableScratchPages: ${{ inputs.driver == 'rolling' && '1' || '0' }}
-      python: ${{ inputs.python != '' && inputs.python || '3.10' }}
-      pytorch: ${{ inputs.pytorch != '' && inputs.pytorch || 'nightly' }}
-      transformers: ${{ inputs.transformers != '' && inputs.transformers || 'v4.49.0' }}
-      PYTEST_TIMEOUT: 600
+      HF_HOME: ${{ github.workspace }}/.hf_home_${{ matrix.test.test_case }}
       PYTORCH_DEBUG_XPU_FALLBACK: '1'
       TRANSFORMERS_TEST_DEVICE_SPEC: 'spec.py'
     steps:
@@ -73,39 +145,38 @@ jobs:
           path: transformers
       - name: Prepare OS environment
         run: |
-          sudo apt-get update
-          sudo apt-get install -y \
-            espeak-ng \
-            git-lfs \
-            pkg-config \
-            libavcodec-dev \
-            libavdevice-dev \
-            libavfilter-dev \
-            libavformat-dev \
-            libavutil-dev \
-            libswresample-dev \
-            libswscale-dev
-          git lfs install
+          # as jobs might run in parallel on the same system, apt-get might
+          # step into the lock hold by other job
+          start_time=$SECONDS
+          while ! sudo apt-get update; do
+            sleep 1;
+            if (( $SECONDS - start_time > 60 )); then false; fi
+          done
+          while ! sudo apt-get install -y $PACKAGES; do
+            sleep 1;
+            if (( $SECONDS - start_time > 60 )); then false; fi
+          done
+          while ! git lfs install; do
+            sleep 1;
+            if (( $SECONDS - start_time > 60 )); then false; fi
+          done
       - name: Create unique Conda ENV name
         run: |
           echo "CONDA_ENV_NAME=hf_transformers_test_${ZE_AFFINITY_MASK}" >> $GITHUB_ENV
       - name: Prepare Conda ENV
         run: |
           echo "Using Conda ENV name: $CONDA_ENV_NAME"
-          which conda && conda clean -ay
           conda remove --all -y -n $CONDA_ENV_NAME || rm -rf $(dirname ${CONDA_EXE})/../envs/$CONDA_ENV_NAME
           conda create -y -n $CONDA_ENV_NAME python=${{ env.python }}
           source activate $CONDA_ENV_NAME
-          pip install junitparser pytest-timeout
+          pip install junitparser pytest-timeout pytest-shard
       - name: Prepare Stock XPU Pytorch
         run: |
-          pwd
           source activate $CONDA_ENV_NAME
-          if [ -z "${{ inputs.nightly_whl }}" ]; then
-            pip install torch torchvision torchaudio --pre --index-url https://download.pytorch.org/whl/nightly/xpu
-          else
-            pip install torch==$(echo ${{ inputs.nightly_whl }}) torchvision torchaudio --pre --index-url https://download.pytorch.org/whl/nightly/xpu
-          fi
+          pip install $TORCH_INDEX \
+            torch==${{ needs.prepare.outputs.torch }} \
+            torchvision==${{ needs.prepare.outputs.torchvision }} \
+            torchaudio==${{ needs.prepare.outputs.torchaudio }}
       - name: Prepare Transformers
         run: |
           pwd
@@ -113,18 +184,19 @@ jobs:
           cd transformers
           pip install -e .
           pip install -e ".[dev-torch,testing,video]"
-          rm -rf tests_log && mkdir -p tests_log
+          rm -rf logs && mkdir -p logs
           rm -rf reports
           cp ${{ github.workspace }}/torch-xpu-ops/.github/scripts/spec.py ./
       - name: Report installed versions
         run: |
           source activate $CONDA_ENV_NAME
+          LOGS_DIR="${{ github.workspace }}/transformers/logs"
           echo "pip installed packages:"
-          pip list | tee ${{ github.workspace }}/transformers/tests_log/pip_list.txt
+          pip list | tee "$LOGS_DIR/pip_list-${{ matrix.test.test_case }}.txt"
           echo "lspci gpu devices:"
-          lspci -d ::0380 | tee ${{ github.workspace }}/transformers/tests_log/lspci_0380.txt
+          lspci -d ::0380 | tee "$LOGS_DIR/lspci_0380-${{ matrix.test.test_case }}.txt"
           echo "GPU render nodes:"
-          cat /sys/class/drm/render*/device/device | tee ${{ github.workspace }}/transformers/tests_log/device_IDs.txt
+          cat /sys/class/drm/render*/device/device | tee "$LOGS_DIR/device_IDs-${{ matrix.test.test_case }}.txt"
           echo "xpu-smi output:"
           xpu-smi discovery -y --json --dump -1
       - name: Sanity check installed packages
@@ -139,88 +211,14 @@ jobs:
       - name: Clean HF home directory and cache
         run: |
           rm -rf ${{ env.HF_HOME }}
-      - name: Run -k backbone tests
+      - name: Run tests
         env:
-          TEST_CASE: 'tests_backbone'
+          TEST_CASE: ${{matrix.test.test_case}}
         run: |
           source activate $CONDA_ENV_NAME
           cd transformers
-          # Excluding tests due to:
-          # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
           python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml \
-            --ignore=tests/models/marian/test_modeling_marian.py \
-            -k backbone tests || true
-      - name: Run tests/*.py
-        env:
-          TEST_CASE: 'tests_py'
-        run: |
-          source activate $CONDA_ENV_NAME
-          cd transformers
-          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/*.py || true
-      - name: Run tests/generation
-        env:
-          TEST_CASE: 'tests_generation'
-        run: |
-          source activate $CONDA_ENV_NAME
-          cd transformers
-          # Excluding tests due to:
-          # * torch.distributed.* not yet supported by XPU
-          pattern="not TestFSDPGeneration"
-          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/generation -k "$pattern" || true
-      - name: Run tests/models
-        env:
-          TEST_CASE: 'tests_models'
-        run: |
-          source activate $CONDA_ENV_NAME
-          cd transformers
-          # Excluding tests due to:
-          # * https://github.com/pytorch/pytorch/issues/140965 (aten::_linalg_eigvals)
-          # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
-          pattern=" \
-            not test_resize_embeddings_untied and \
-            not test_resize_tokens_embeddings"
-          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml \
-            -k "$pattern" --ignore=tests/models/marian/test_modeling_marian.py \
-            tests/models || true
-      - name: Run tests/pipelines
-        env:
-          TEST_CASE: 'tests_pipelines'
-        run: |
-          source activate $CONDA_ENV_NAME
-          cd transformers
-          # Some tests are known to fail w/o clear pattern
-          # TODO: drop ||true after triage and fixes
-          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml tests/pipelines || true
-      - name: Run tests/trainer
-        env:
-          TEST_CASE: 'tests_trainer'
-        run: |
-          source activate $CONDA_ENV_NAME
-          cd transformers
-          # Excluding tests due to:
-          # * Some ray tests hang, reason unknown
-          # * torch.distributed.* not yet supported by XPU
-          pattern=" \
-            not ray and \
-            not TestTrainerDistributed and \
-            not TestTrainerDistributedXPU and \
-            not TestFSDPTrainer"
-          python3 -m pytest -rsf --make-reports=$TEST_CASE tests/trainer --junit-xml=reports/$TEST_CASE.xml -k "$pattern" || \
-            true
-      - name: Run tests/utils
-        env:
-          TEST_CASE: 'tests_utils'
-        run: |
-          source activate $CONDA_ENV_NAME
-          cd transformers
-          # Excluding tests due to:
-          # * Network proxy connection issue, reason unknown
-          pattern="not test_load_img_url_timeout"
-          # 'tests/utils/test_import_utils.py' invalidates state of the test engine causing
-          # next tests to fail. See: https://github.com/huggingface/transformers/issues/36267
-          python3 -m pytest -rsf --make-reports=$TEST_CASE --junit-xml=reports/$TEST_CASE.xml \
-            -k "$pattern" --ignore=tests/utils/test_import_utils.py \
-            tests/utils || true
+            -k "${{ matrix.test.filter}}" ${{ matrix.test.cmd }} || true
       - name: Check for errors in tests
         run: |
           source activate $CONDA_ENV_NAME
@@ -230,9 +228,55 @@ jobs:
         run: |
           du -sh ${{ env.HF_HOME }} || true
           rm -rf ${{ env.HF_HOME }}
+      - name: Print environment
+        if: ${{ ! cancelled() }}
+        uses: ./torch-xpu-ops/.github/actions/print-environment
+        with:
+          conda: $CONDA_ENV_NAME
+          pip_packages: 'accelerate transformers'
+          to: 'transformers/logs/environment-${{ matrix.test.test_case }}.md'
+      - name: Upload reports
+        if: ${{ ! cancelled() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: reports-${{ matrix.test.test_case }}-${{ github.event.pull_request.number || github.sha }}
+          path: ${{ github.workspace }}/transformers/reports
+      - name: Upload logs
+        if: ${{ ! cancelled() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: logs-${{ matrix.test.test_case }}-${{ github.event.pull_request.number || github.sha }}
+          path: ${{ github.workspace }}/transformers/logs
+
+  report:
+    needs: tests
+    if: "always()"
+    runs-on: ${{ inputs.runner != '' && inputs.runner || 'linux.idc.xpu' }}
+    steps:
+      - name: Download reports
+        uses: actions/download-artifact@v4
+        with:
+          pattern: 'reports-*'
+          path: 'transformers/reports/'
+          merge-multiple: true
+      - name: Download logs
+        if: ${{ ! cancelled() }}
+        uses: actions/download-artifact@v4
+        with:
+          pattern: 'logs-*'
+          path: 'transformers/logs/'
+          merge-multiple: true
+      - name: Checkout torch-xpu-ops
+        if: ${{ ! cancelled() }}
+        uses: actions/checkout@v4
+        with:
+          path: torch-xpu-ops
       - name: Print results table
         if: ${{ ! cancelled() }}
         run: |
+          ls transformers/reports/
+          ls transformers/logs/
+          find . -name "*.xml"
           # Helper function to return number preceeding given pattern, i.e:
           #   === 25 failed, 11 warnings, 0 errors ===
           # Call as follows:
@@ -322,15 +366,9 @@ jobs:
           } >> $GITHUB_STEP_SUMMARY
       - name: Print environment
         if: ${{ ! cancelled() }}
-        uses: ./torch-xpu-ops/.github/actions/print-environment
-        with:
-          conda: $CONDA_ENV_NAME
-          pip_packages: 'accelerate transformers'
-      - name: Upload Test log
-        if: ${{ ! cancelled() }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: Torch-XPU-Transformers-Log-${{ github.event.pull_request.number || github.sha }}
-          path: | 
-            ${{ github.workspace }}/transformers/reports
-            ${{ github.workspace }}/transformers/tests_log
+        run: |
+          environment=$(find transformers/logs -name "environment-*.md" | head -1)
+          cat $environment >> $GITHUB_STEP_SUMMARY
+          # we expect environments to be identical except for the ZE_AFFINITY_MASK line
+          find transformers/logs -name "environment-*.md" | xargs sed -i '/ZE_AFFINITY_MASK/d'
+          diff $(find transformers/logs -name "environment-*.md")
