update

diff --git a/.github/workflows/_linux_transformers.yml b/.github/workflows/_linux_transformers.yml
--- a/.github/workflows/_linux_transformers.yml
+++ b/.github/workflows/_linux_transformers.yml
@@ -162,7 +162,47 @@ jobs:
       fail-fast: false
       max-parallel: 1
       matrix:
-        test_case: [tests_backbone,tests_py,tests_generation,tests_models_4_0,tests_models_4_1,tests_models_4_2,tests_models_4_3,tests_trainer,tests_utils]
+        test:
+          # Excluding tests due to:
+          # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
+          - test_case: 'tests_backbone'
+            cmd: '--ignore=tests/models/marian/test_modeling_marian.py -k backbone tests'
+          - test_case: "tests_py"
+            cmd: "tests/*.py"
+          # Excluding tests due to:
+          # * torch.distributed.* not yet supported by XPU
+          - test_case: 'tests_generation'
+            cmd: 'tests/generation'
+            filter: 'not TestFSDPGeneration'
+          # breaking for each shard to take ~15-30 minutes to complete
+          # Excluding tests due to:
+          # * https://github.com/pytorch/pytorch/issues/140965 (aten::_linalg_eigvals)
+          # * https://github.com/huggingface/transformers/issues/36267 (marian tests)
+          - test_case: 'tests_models_0'
+            cmd: 'tests/models --num-shards 4 --shard-id 0 --ignore=tests/models/marian/test_modeling_marian.py'
+            filter: 'not test_resize_embeddings_untied and not test_resize_tokens_embeddings'
+          - test_case: 'tests_models_1'
+            cmd: 'tests/models --num-shards 4 --shard-id 1 --ignore=tests/models/marian/test_modeling_marian.py'
+            filter: 'not test_resize_embeddings_untied and not test_resize_tokens_embeddings'
+          - test_case: 'tests_models_2'
+            cmd: 'tests/models --num-shards 4 --shard-id 2 --ignore=tests/models/marian/test_modeling_marian.py'
+            filter: 'not test_resize_embeddings_untied and not test_resize_tokens_embeddings'
+          - test_case: 'tests_models_3'
+            cmd: 'tests/models --num-shards 4 --shard-id 3 --ignore=tests/models/marian/test_modeling_marian.py'
+            filter: 'not test_resize_embeddings_untied and not test_resize_tokens_embeddings'
+          # Excluding tests due to:
+          # * Some ray tests hang, reason unknown
+          # * torch.distributed.* not yet supported by XPU
+          - test_case: 'tests_trainer'
+            cmd: 'tests/trainer'
+            filter: 'not ray and not TestTrainerDistributed and not TestTrainerDistributedXPU and not TestFSDPTrainer'
+          # Excluding tests due to:
+          # * Network proxy connection issue, reason unknown
+          # *'tests/utils/test_import_utils.py' invalidates state of the test engine causing
+          #   next tests to fail. See: https://github.com/huggingface/transformers/issues/36267
+          - test_case: 'tests_utils'
+            cmd: '--ignore=tests/utils/test_import_utils.py tests/utils'
+            filter: 'not test_load_img_url_timeout'
     steps:
       - name: Checkout torch-xpu-ops
         uses: actions/checkout@v4
@@ -177,7 +217,7 @@ jobs:
       - name: Prepare test vars
         run: |
           echo "HF_HOME=$HOME/.hf_home_of_transformers_test" >> $GITHUB_ENV
-          echo "TEST_CASE=${{matrix.test_case}}" >> $GITHUB_ENV
+          echo "TEST_CASE=${{matrix.test.test_case}}" >> $GITHUB_ENV
       - name: Report HF cache directory
         run: |
           if [ -d "$HF_HOME" ]; then
@@ -205,6 +245,11 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: ${{ env.python }}
+      - name: Check python
+        run: |
+          which python && python -V
+          which pip && pip list
+          pip install -U pip wheel setuptools
       - name: Prepare pytorch and deps
         run: |
           pip install junitparser
@@ -246,13 +291,14 @@ jobs:
           pip show torchaudio | grep Version | grep xpu
           pip show torchvision | grep Version | grep xpu
           python -c 'import torch; exit(not torch.xpu.is_available())'
-      - name: Run ${{ matrix.test_case }} on ${{ needs.prepare.outputs.hostname }}
-        uses: ./torch-xpu-ops/.github/actions/transformers
-        with:
-          test_case: ${{ matrix.test_case }}
+      - name: Run tests on ${{ needs.prepare.outputs.hostname }}
+        run: |
+          cd transformers
+          python -m pytest --make-reports=${TEST_CASE} --junit-xml=reports/${TEST_CASE}.xml \
+                  -k "${{ matrix.test.filter}}" ${{ matrix.test.cmd }} || true
       - name: Check for errors in tests
         run: |
-          python3 torch-xpu-ops/.github/scripts/check-transformers.py transformers/reports/*.xml
+          python torch-xpu-ops/.github/scripts/check-transformers.py transformers/reports/*.xml
       - name: Print environment
         if: ${{ ! cancelled() }}
         uses: ./torch-xpu-ops/.github/actions/print-environment
@@ -271,13 +317,13 @@ jobs:
         if: ${{ ! cancelled() }}
         uses: actions/upload-artifact@v4
         with:
-          name: reports-${{ matrix.test_case }}-${{ github.event.pull_request.number || github.sha }}
+          name: reports-${{ matrix.test.test_case }}-${{ github.event.pull_request.number || github.sha }}
           path: ${{ github.workspace }}/transformers/reports
       - name: Upload logs
         if: ${{ ! cancelled() }}
         uses: actions/upload-artifact@v4
         with:
-          name: logs-${{ matrix.test_case }}-${{ github.event.pull_request.number || github.sha }}
+          name: logs-${{ matrix.test.test_case }}-${{ github.event.pull_request.number || github.sha }}
           path: ${{ github.workspace }}/transformers/logs
 
   report:
@@ -342,7 +388,7 @@ jobs:
       - name: Print baseline difference
         if: ${{ ! cancelled() }}
         run: |
-          python3 torch-xpu-ops/.github/scripts/check-transformers.py transformers/reports/*.xml >> $GITHUB_STEP_SUMMARY || true
+          python torch-xpu-ops/.github/scripts/check-transformers.py transformers/reports/*.xml >> $GITHUB_STEP_SUMMARY || true
       - name: Print failure lines
         if: ${{ ! cancelled() }}
         run: |
