modify pt2e summary

diff --git a/.github/workflows/nightly_ondemand_whl.yml b/.github/workflows/nightly_ondemand_whl.yml
--- a/.github/workflows/nightly_ondemand_whl.yml
+++ b/.github/workflows/nightly_ondemand_whl.yml
@@ -294,11 +294,12 @@ jobs:
               exit ${exit_label}
             fi
           else
-            source activate e2e_ci
-            cp -r ${{ github.workspace }}/.github/scripts/summary_pt2e.py ${{ github.workspace }}/upload_files
-            cd ${{ github.workspace }}/upload_files
-            python summary_pt2e.py ${{ github.workspace }}/upload_files/inductor_log/pt2e
-            rm -rf summary_pt2e.py
+            find ${{ github.workspace }}/upload_files/ -name "summary.csv" | xargs cat
+            failed_num=$(find ${{ github.workspace }}/upload_files/ -name "summary.csv" |xargs grep ',failed' |wc -l)
+            if [ ${failed_num} -ne 0 ];then
+              echo "PT2E has failures!"
+              exit 1
+            fi
           fi
       - name: Upload Inductor XPU E2E Data
         if: ${{ ! cancelled() }}
